language: node_js

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm i -g yarn@latest

install:
  - yarn install --frozen-lockfile

matrix:
  include:
    - node_js: 'lts/*'
      name: 'LTS/*'
      script:
        - 'commitlint-travis'
        - 'yarn lint'
        - 'yarn test'
      env:
        - CACHE_NAME=latest
    - node_js: 'lts/dubnium'
      name: 'LTS/Dubnium'
      script:
        - 'commitlint-travis'
        - 'yarn lint'
        - 'yarn test'
      env:
        - CACHE_NAME=lts
    - node_js: 'lts/*'
      name: 'Canary'
      # script: 'yarn canarist || :'
      script: 'yarn canarist'
      env:
        - CACHE_NAME=canary
