language: node_js

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm i -g yarn@latest

install:
  - yarn install --frozen-lockfile

matrix:
  include:
    - node_js: '10.13'
      name: 'LTS Maintenance'
      script: 'yarn test'
      env:
        - CACHE_NAME=maintenance
    - node_js: '12.13'
      name: 'LTS Active'
      before_script:
        - 'commitlint-travis'
        - 'yarn lint'
      script: 'yarn test'
      env:
        - CACHE_NAME=active
    - node_js: '12.13'
      name: 'Canary'
      script: 'yarn canarist'
      env:
        - CACHE_NAME=canary
