language: node_js

before_install:
  - npm install -g yarn@1

install:
  - yarn install

before_script:
  - yarn bootstrap

script:
  - yarn test
  - yarn lint

node_js:
  - '8'
  - '9'

env:
  - NODE_ENV=development
