name: CI

on:
  push:
    branches:
      - master

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Rebase next against master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/untool/untool.git
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          ./scripts/rebase.sh master next
